# Generated by Django 3.1.4 on 2020-12-09 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('required_level', models.PositiveSmallIntegerField(default=0, verbose_name='Требуемый уровень')),
                ('required_mana', models.PositiveSmallIntegerField(default=10, verbose_name='Требуемая мана')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='skins/', verbose_name='Изображение')),
                ('cost', models.PositiveIntegerField(default=1000, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Скин',
                'verbose_name_plural': 'Скины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('skill', models.ManyToManyField(to='registration.SkillModel', verbose_name='Скилы')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень')),
                ('health', models.PositiveSmallIntegerField(default=100, verbose_name='Здоровье')),
                ('mana', models.PositiveSmallIntegerField(default=50, verbose_name='Мана')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='Монеты')),
                ('active', models.BooleanField(default=False, verbose_name='Активный персонаж')),
                ('skin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.skinmodel', verbose_name='Скин')),
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.stylemodel', verbose_name='Класс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['style'],
            },
        ),
    ]
