# Generated by Django 3.1.4 on 2020-12-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinmodel',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.stylemodel', verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
